# Generated by Django 5.1.2 on 2024-11-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Student_id', models.IntegerField()),
                ('contribution', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
