# Generated by Django 5.1.2 on 2024-11-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_member_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Student_id', models.CharField(blank=True, max_length=10, null=True)),
                ('contribution', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Team_members',
        ),
    ]
