# Generated by Django 5.1.2 on 2024-11-02 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_topic_room_host_messase_room_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messase',
            new_name='Message',
        ),
    ]
